# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license
#
# Copyright (C) 2025 Ultralytics, Jehyeon Park
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

from ultralytics.utils import IterableSimpleNamespace

def get_args_kwargs(split):
    return ((), {
        'img_path': f'/vida/falldown/yolo-mmpatient-new/{split}/images',
        'imgsz': 640,
        'batch_size': 32,
        'augment': True,
        'rect': False,
        'cache': None,
        'single_cls': False,
        'stride': 32,
        'pad': 0.5,
        'prefix': '\x1b[34m\x1b[1mval: \x1b[0m',
        'classes': None,
        'fraction': 1.0,
        'hyp': IterableSimpleNamespace(
            agnostic_nms=False,
            amp=True,
            augment=True,
            auto_augment='randaugment',
            batch=16,
            bgr=0.0,
            box=7.5,
            cache=False,
            cfg=None,
            classes=None,
            close_mosaic=10,
            cls=0.5,
            conf=None,
            copy_paste=0.0,
            copy_paste_mode='flip',
            cos_lr=False,
            data='data_mmpatient_full.yaml',
            degrees=0.0,
            deterministic=True,
            device=0,
            dfl=1.5,
            dnn=False,
            dropout=0.0,
            dynamic=False,
            embed=None,
            epochs=2000,
            erasing=0.4,
            exist_ok=False,
            fliplr=0.0,
            flipud=0.0,
            format='torchscript',
            fraction=1.0,
            freeze=None,
            half=False,
            hsv_h=0.015,
            hsv_s=0.7,
            hsv_v=0.4,
            imgsz=640,
            int8=False,
            iou=0.7,
            keras=False,
            kobj=1.0,
            line_width=None,
            lr0=0.01,
            lrf=0.01,
            mask_ratio=4,
            max_det=300,
            mixup=0.0,
            mode='train',
            model='yolo11x-pose.pt',
            momentum=0.937,
            mosaic=1.0,
            multi_scale=False,
            name='train',
            nbs=64, nms=False,
            opset=None,
            optimize=False,
            optimizer='auto',
            overlap_mask=True,
            patience=100,
            perspective=0.0,
            plots=True,
            pose=12.0,
            pretrained=True,
            profile=False,
            project=None,
            rect=False,
            resume=False,
            retina_masks=False,
            save=True,
            save_conf=False,
            save_crop=False,
            save_dir='runs/pose/train',
            save_frames=False, save_json=False,
            save_period=-1, save_txt=False,
            scale=0.5,
            seed=0,
            shear=0.0,
            show=False,
            show_boxes=True,
            show_conf=True,
            show_labels=True,
            simplify=True,
            single_cls=False,
            source=None,
            split='val',
            stream_buffer=False,
            task='pose',
            time=None,
            tracker='botsort.yaml',
            translate=0.1,
            val=True,
            verbose=True,
            vid_stride=1,
            visualize=False,
            warmup_bias_lr=0.1,
            warmup_epochs=3.0,
            warmup_momentum=0.8,
            weight_decay=0.0005,
            workers=8,
            workspace=None,

            # loss_weights = {
            #     'box': 7.5,
            #     'pose': 12.0,
            #     'kobj': 5.0,
            #     'cls': 2.0,
            #     'dfl': 0.1,
            # },

            # Original
            loss_weights = {
                'box': 7.5,
                'pose': 12.0,
                'kobj': 1.0,
                'cls': 0.5,
                'dfl': 1.5
            }
        ),
    })